/* The following code was generated by JFlex 1.4.3 on 27/07/11 14:49 */

/*
 * Copyright 2008 Ayman Al-Sairafi ayman.alsairafi@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License
 *       at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package jsyntaxpane.lexers;


import jsyntaxpane.Token;
import jsyntaxpane.TokenType;
 

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/07/11 14:49 from the specification file
 * <tt>/mnt/data/Code/java/praxis/jsyntaxpane/praxis-jsyntaxpane/src/main/jflex/jsyntaxpane/lexers/praxisscript.flex</tt>
 */
public final class PraxisScriptLexer extends DefaultJFlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\6\1\3\1\2\1\0\1\3\1\1\16\6\4\0\1\3\1\0"+
    "\1\23\1\4\1\5\2\0\1\0\3\0\1\22\1\0\1\22\1\20"+
    "\1\0\1\7\1\15\2\14\4\16\2\10\1\0\1\31\5\0\3\13"+
    "\1\17\1\21\1\17\5\5\1\11\13\5\1\12\2\5\1\27\1\24"+
    "\1\30\1\0\1\5\1\0\1\37\2\13\1\17\1\35\1\36\5\5"+
    "\1\40\5\5\1\33\1\41\1\32\1\34\2\5\1\12\2\5\1\25"+
    "\1\0\1\26\1\0\41\6\2\0\4\5\4\0\1\5\2\0\1\6"+
    "\7\0\1\5\4\0\1\5\5\0\27\5\1\0\37\5\1\0\u013f\5"+
    "\31\0\162\5\4\0\14\5\16\0\5\5\11\0\1\5\21\0\130\6"+
    "\5\0\23\6\12\0\1\5\13\0\1\5\1\0\3\5\1\0\1\5"+
    "\1\0\24\5\1\0\54\5\1\0\46\5\1\0\5\5\4\0\202\5"+
    "\1\0\4\6\3\0\105\5\1\0\46\5\2\0\2\5\6\0\20\5"+
    "\41\0\46\5\2\0\1\5\7\0\47\5\11\0\21\6\1\0\27\6"+
    "\1\0\3\6\1\0\1\6\1\0\2\6\1\0\1\6\13\0\33\5"+
    "\5\0\3\5\15\0\4\6\14\0\6\6\13\0\32\5\5\0\13\5"+
    "\16\6\7\0\12\6\4\0\2\5\1\6\143\5\1\0\1\5\10\6"+
    "\1\0\6\6\2\5\2\6\1\0\4\6\2\5\12\6\3\5\2\0"+
    "\1\5\17\0\1\6\1\5\1\6\36\5\33\6\2\0\3\5\60\0"+
    "\46\5\13\6\1\5\u014f\0\3\6\66\5\2\0\1\6\1\5\20\6"+
    "\2\0\1\5\4\6\3\0\12\5\2\6\2\0\12\6\21\0\3\6"+
    "\1\0\10\5\2\0\2\5\2\0\26\5\1\0\7\5\1\0\1\5"+
    "\3\0\4\5\2\0\1\6\1\5\7\6\2\0\2\6\2\0\3\6"+
    "\11\0\1\6\4\0\2\5\1\0\3\5\2\6\2\0\12\6\4\5"+
    "\15\0\3\6\1\0\6\5\4\0\2\5\2\0\26\5\1\0\7\5"+
    "\1\0\2\5\1\0\2\5\1\0\2\5\2\0\1\6\1\0\5\6"+
    "\4\0\2\6\2\0\3\6\13\0\4\5\1\0\1\5\7\0\14\6"+
    "\3\5\14\0\3\6\1\0\11\5\1\0\3\5\1\0\26\5\1\0"+
    "\7\5\1\0\2\5\1\0\5\5\2\0\1\6\1\5\10\6\1\0"+
    "\3\6\1\0\3\6\2\0\1\5\17\0\2\5\2\6\2\0\12\6"+
    "\1\0\1\5\17\0\3\6\1\0\10\5\2\0\2\5\2\0\26\5"+
    "\1\0\7\5\1\0\2\5\1\0\5\5\2\0\1\6\1\5\6\6"+
    "\3\0\2\6\2\0\3\6\10\0\2\6\4\0\2\5\1\0\3\5"+
    "\4\0\12\6\1\0\1\5\20\0\1\6\1\5\1\0\6\5\3\0"+
    "\3\5\1\0\4\5\3\0\2\5\1\0\1\5\1\0\2\5\3\0"+
    "\2\5\3\0\3\5\3\0\10\5\1\0\3\5\4\0\5\6\3\0"+
    "\3\6\1\0\4\6\11\0\1\6\17\0\11\6\11\0\1\5\7\0"+
    "\3\6\1\0\10\5\1\0\3\5\1\0\27\5\1\0\12\5\1\0"+
    "\5\5\4\0\7\6\1\0\3\6\1\0\4\6\7\0\2\6\11\0"+
    "\2\5\4\0\12\6\22\0\2\6\1\0\10\5\1\0\3\5\1\0"+
    "\27\5\1\0\12\5\1\0\5\5\2\0\1\6\1\5\7\6\1\0"+
    "\3\6\1\0\4\6\7\0\2\6\7\0\1\5\1\0\2\5\4\0"+
    "\12\6\22\0\2\6\1\0\10\5\1\0\3\5\1\0\27\5\1\0"+
    "\20\5\4\0\6\6\2\0\3\6\1\0\4\6\11\0\1\6\10\0"+
    "\2\5\4\0\12\6\22\0\2\6\1\0\22\5\3\0\30\5\1\0"+
    "\11\5\1\0\1\5\2\0\7\5\3\0\1\6\4\0\6\6\1\0"+
    "\1\6\1\0\10\6\22\0\2\6\15\0\60\5\1\6\2\5\7\6"+
    "\4\0\10\5\10\6\1\0\12\6\47\0\2\5\1\0\1\5\2\0"+
    "\2\5\1\0\1\5\2\0\1\5\6\0\4\5\1\0\7\5\1\0"+
    "\3\5\1\0\1\5\1\0\1\5\2\0\2\5\1\0\4\5\1\6"+
    "\2\5\6\6\1\0\2\6\1\5\2\0\5\5\1\0\1\5\1\0"+
    "\6\6\2\0\12\6\2\0\2\5\42\0\1\5\27\0\2\6\6\0"+
    "\12\6\13\0\1\6\1\0\1\6\1\0\1\6\4\0\2\6\10\5"+
    "\1\0\42\5\6\0\24\6\1\0\2\6\4\5\4\0\10\6\1\0"+
    "\44\6\11\0\1\6\71\0\42\5\1\0\5\5\1\0\2\5\1\0"+
    "\7\6\3\0\4\6\6\0\12\6\6\0\6\5\4\6\106\0\46\5"+
    "\12\0\51\5\7\0\132\5\5\0\104\5\5\0\122\5\6\0\7\5"+
    "\1\0\77\5\1\0\1\5\1\0\4\5\2\0\7\5\1\0\1\5"+
    "\1\0\4\5\2\0\47\5\1\0\1\5\1\0\4\5\2\0\37\5"+
    "\1\0\1\5\1\0\4\5\2\0\7\5\1\0\1\5\1\0\4\5"+
    "\2\0\7\5\1\0\7\5\1\0\27\5\1\0\37\5\1\0\1\5"+
    "\1\0\4\5\2\0\7\5\1\0\47\5\1\0\23\5\16\0\11\6"+
    "\56\0\125\5\14\0\u026c\5\2\0\10\5\12\0\32\5\5\0\113\5"+
    "\3\0\3\5\17\0\15\5\1\0\4\5\3\6\13\0\22\5\3\6"+
    "\13\0\22\5\2\6\14\0\15\5\1\0\3\5\1\0\2\6\14\0"+
    "\64\5\40\6\3\0\1\5\3\0\2\5\1\6\2\0\12\6\41\0"+
    "\3\6\2\0\12\6\6\0\130\5\10\0\51\5\1\6\126\0\35\5"+
    "\3\0\14\6\4\0\14\6\12\0\12\6\36\5\2\0\5\5\u038b\0"+
    "\154\5\224\0\234\5\4\0\132\5\6\0\26\5\2\0\6\5\2\0"+
    "\46\5\2\0\6\5\2\0\10\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\5\1\0\37\5\2\0\65\5\1\0\7\5\1\0\1\5\3\0"+
    "\3\5\1\0\7\5\3\0\4\5\2\0\6\5\4\0\15\5\5\0"+
    "\3\5\1\0\7\5\17\0\4\6\32\0\5\6\20\0\2\5\23\0"+
    "\1\5\13\0\4\6\6\0\6\6\1\0\1\5\15\0\1\5\40\0"+
    "\22\5\36\0\15\6\4\0\1\6\3\0\6\6\27\0\1\5\4\0"+
    "\1\5\2\0\12\5\1\0\1\5\3\0\5\5\6\0\1\5\1\0"+
    "\1\5\1\0\1\5\1\0\4\5\1\0\3\5\1\0\7\5\3\0"+
    "\3\5\5\0\5\5\26\0\44\5\u0e81\0\3\5\31\0\11\5\6\6"+
    "\1\0\5\5\2\0\5\5\4\0\126\5\2\0\2\6\2\0\3\5"+
    "\1\0\137\5\5\0\50\5\4\0\136\5\21\0\30\5\70\0\20\5"+
    "\u0200\0\u19b6\5\112\0\u51a6\5\132\0\u048d\5\u0773\0\u2ba4\5\u215c\0\u012e\5"+
    "\2\0\73\5\225\0\7\5\14\0\5\5\5\0\1\5\1\6\12\5"+
    "\1\0\15\5\1\0\5\5\1\0\1\5\1\0\2\5\1\0\2\5"+
    "\1\0\154\5\41\0\u016b\5\22\0\100\5\2\0\66\5\50\0\15\5"+
    "\3\0\20\6\20\0\4\6\17\0\2\5\30\0\3\5\31\0\1\5"+
    "\6\0\5\5\1\0\207\5\2\0\1\6\4\0\1\5\13\0\12\6"+
    "\7\0\32\5\4\0\1\5\1\0\32\5\12\0\132\5\3\0\6\5"+
    "\2\0\6\5\2\0\6\5\2\0\3\5\3\0\2\5\3\0\2\5"+
    "\22\0\3\6\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\3\1\1\2\1\3\2\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\2\3\1\13\2\14\1\15"+
    "\1\1\2\2\3\4\1\0\3\4\1\0\2\3\1\16"+
    "\2\13\4\4\1\0\2\3\1\13\2\4\1\17\14\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\5\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\104\0\104\0\104\0\104\0\104\0\104"+
    "\0\u0154\0\u0176\0\u0198\0\u01ba\0\104\0\104\0\u01dc\0\u01fe"+
    "\0\104\0\u0220\0\u0242\0\104\0\u0264\0\u0286\0\u02a8\0\u02ca"+
    "\0\u02ec\0\u030e\0\u0330\0\104\0\u0352\0\u0374\0\u0396\0\u03b8"+
    "\0\u03da\0\u03fc\0\u041e\0\u0440\0\u0462\0\104\0\u0484\0\u04a6"+
    "\0\314\0\u04c8\0\u04ea\0\u050c\0\u052e\0\u0550\0\u0572\0\u0594"+
    "\0\u05b6\0\u05d8\0\u05fa\0\u061c\0\u063e\0\u0660\0\u0682\0\u06a4"+
    "\0\u06c6\0\u06e8\0\u070a\0\u072c\0\u074e\0\u0770\0\u0792\0\u07b4"+
    "\0\u07d6\0\u07f8\0\u081a\0\u083c\0\u085e\0\u0880\0\u08a2\0\u08c4"+
    "\0\u08e6";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\6\1\7\1\3\1\10"+
    "\1\11\3\7\3\11\1\7\1\12\1\7\1\3\1\13"+
    "\1\3\1\14\1\15\1\16\1\17\1\20\1\21\3\7"+
    "\1\22\3\7\1\23\1\24\1\25\20\23\1\26\1\27"+
    "\15\23\44\0\1\3\42\0\1\5\36\0\1\6\1\30"+
    "\1\31\37\6\5\0\13\7\1\0\1\7\10\0\10\7"+
    "\7\0\1\32\1\33\1\34\1\35\1\0\1\36\1\37"+
    "\1\36\1\34\1\40\1\41\13\0\1\41\1\34\1\0"+
    "\1\34\10\0\2\11\1\34\2\0\3\11\1\34\1\40"+
    "\1\41\13\0\1\41\1\34\1\0\1\34\10\0\2\40"+
    "\3\0\3\40\30\0\13\7\1\0\1\7\10\0\1\7"+
    "\1\42\6\7\5\0\13\7\1\0\1\7\10\0\5\7"+
    "\1\43\2\7\1\23\2\0\20\23\2\0\15\23\2\0"+
    "\1\25\37\0\2\44\1\0\4\44\1\45\4\44\2\45"+
    "\1\46\23\44\2\0\1\31\46\0\1\32\1\33\1\34"+
    "\2\0\1\36\1\37\1\36\1\34\1\40\1\41\13\0"+
    "\1\41\1\34\1\0\1\34\10\0\2\33\3\0\3\33"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\12\0\1\47"+
    "\1\50\2\0\5\50\1\0\1\50\13\0\3\50\11\0"+
    "\1\51\1\33\1\34\2\0\3\51\1\34\1\40\1\41"+
    "\13\0\1\41\1\34\1\0\1\34\10\0\1\36\1\33"+
    "\1\34\2\0\3\36\1\34\1\40\1\41\13\0\1\41"+
    "\1\34\1\0\1\34\10\0\2\40\3\0\3\40\1\34"+
    "\1\0\1\41\13\0\1\41\1\34\12\0\2\52\3\0"+
    "\3\52\3\0\1\53\24\0\13\7\1\0\1\7\10\0"+
    "\2\7\1\54\5\7\5\0\13\7\1\0\1\7\10\0"+
    "\6\7\1\55\1\7\7\0\1\46\4\0\3\46\32\0"+
    "\1\56\4\0\3\56\32\0\1\47\1\50\1\34\1\0"+
    "\5\50\1\0\1\50\13\0\3\50\1\34\10\0\2\57"+
    "\1\34\1\0\5\57\1\0\1\57\13\0\3\57\1\34"+
    "\10\0\1\60\1\33\1\34\2\0\3\60\1\34\1\40"+
    "\1\41\13\0\1\41\1\34\1\0\1\34\10\0\2\52"+
    "\3\0\3\52\1\34\16\0\1\34\12\0\2\52\3\0"+
    "\3\52\30\0\13\7\1\0\1\7\10\0\3\7\1\61"+
    "\4\7\5\0\13\7\1\0\1\7\10\0\7\7\1\54"+
    "\7\0\2\62\1\34\1\0\5\62\1\0\1\62\13\0"+
    "\3\62\1\34\10\0\1\63\1\33\1\34\2\0\3\63"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\64\1\34\1\0\5\64\1\0\1\64\13\0"+
    "\3\64\1\34\10\0\1\65\1\33\1\34\2\0\3\65"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\66\1\34\1\0\5\66\1\0\1\66\13\0"+
    "\3\66\1\34\10\0\1\67\1\33\1\34\2\0\3\67"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\70\1\34\1\0\5\70\1\0\1\70\13\0"+
    "\3\70\1\34\10\0\1\71\1\33\1\34\2\0\3\71"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\72\1\34\1\0\5\72\1\0\1\72\13\0"+
    "\3\72\1\34\10\0\1\73\1\33\1\34\2\0\3\73"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\74\1\34\1\0\5\74\1\0\1\74\13\0"+
    "\3\74\1\34\10\0\1\75\1\33\1\34\2\0\3\75"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\76\1\34\1\0\5\76\1\0\1\76\13\0"+
    "\3\76\1\34\10\0\1\77\1\33\1\34\2\0\3\77"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\100\1\34\1\0\5\100\1\0\1\100\13\0"+
    "\3\100\1\34\10\0\1\101\1\33\1\34\2\0\3\101"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\102\1\34\1\0\5\102\1\0\1\102\13\0"+
    "\3\102\1\34\10\0\1\103\1\33\1\34\2\0\3\103"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\104\1\34\1\0\5\104\1\0\1\104\13\0"+
    "\3\104\1\34\10\0\1\105\1\33\1\34\2\0\3\105"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\106\1\34\1\0\5\106\1\0\1\106\13\0"+
    "\3\106\1\34\10\0\1\107\1\33\1\34\2\0\3\107"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\110\1\34\1\0\5\110\1\0\1\110\13\0"+
    "\3\110\1\34\10\0\1\111\1\33\1\34\2\0\3\111"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\112\1\34\1\0\5\112\1\0\1\112\13\0"+
    "\3\112\1\34\10\0\1\113\1\33\1\34\2\0\3\113"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\2\114\1\34\1\0\5\114\1\0\1\114\13\0"+
    "\3\114\1\34\10\0\1\115\1\33\1\34\2\0\3\115"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\12\0\1\34\26\0\1\34\10\0\1\116\1\33\1\34"+
    "\2\0\3\116\1\34\1\40\1\41\13\0\1\41\1\34"+
    "\1\0\1\34\10\0\1\117\1\33\1\34\2\0\3\117"+
    "\1\34\1\40\1\41\13\0\1\41\1\34\1\0\1\34"+
    "\10\0\1\120\1\33\1\34\2\0\3\120\1\34\1\40"+
    "\1\41\13\0\1\41\1\34\1\0\1\34\10\0\1\121"+
    "\1\33\1\34\2\0\3\121\1\34\1\40\1\41\13\0"+
    "\1\41\1\34\1\0\1\34\10\0\2\33\1\34\2\0"+
    "\3\33\1\34\1\40\1\41\13\0\1\41\1\34\1\0"+
    "\1\34\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2312];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\7\1\6\11\4\1\2\11\2\1\1\11"+
    "\2\1\1\11\1\0\3\1\1\0\2\1\1\11\6\1"+
    "\1\0\2\1\1\11\17\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /**
     * Create an empty lexer, yyrset will be called later to reset and assign
     * the reader
     */
    public PraxisScriptLexer() {
        super();
    }

    @Override
    public int yychar() {
        return yychar;
    }

    private static final byte BRACE     = 1;
    private static final byte SUBCOMMAND   = 2;



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PraxisScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public PraxisScriptLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1746) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 15: 
          { return token(TokenType.KEYWORD);
          }
        case 16: break;
        case 6: 
          { return token(TokenType.OPERATOR,  BRACE);
          }
        case 17: break;
        case 5: 
          { yybegin(STRING); 
                                    tokenStart = yychar; 
                                    tokenLength = 1;
          }
        case 18: break;
        case 13: 
          { yybegin(YYINITIAL); 
                                     // length also includes the trailing quote
                                     return token(TokenType.STRING, tokenStart, tokenLength + 1);
          }
        case 19: break;
        case 10: 
          { return token(TokenType.OPERATOR);
          }
        case 20: break;
        case 14: 
          { tokenLength += 2;
          }
        case 21: break;
        case 3: 
          { return token(TokenType.IDENTIFIER);
          }
        case 22: break;
        case 9: 
          { return token(TokenType.OPERATOR, -SUBCOMMAND);
          }
        case 23: break;
        case 2: 
          { return token(TokenType.COMMENT);
          }
        case 24: break;
        case 8: 
          { return token(TokenType.OPERATOR,  SUBCOMMAND);
          }
        case 25: break;
        case 12: 
          { yybegin(YYINITIAL);
          }
        case 26: break;
        case 4: 
          { return token(TokenType.NUMBER);
          }
        case 27: break;
        case 11: 
          { tokenLength += yylength();
          }
        case 28: break;
        case 1: 
          { 
          }
        case 29: break;
        case 7: 
          { return token(TokenType.OPERATOR, -BRACE);
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return null;
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
